bookmarks/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    # 使用其他社交账户登录的url
    path('social-auth',
         include('social_django.urls',namespace='social')),
    # 图片应用
    path('images/',include('images.urls',namespace='images')),
]

# 只有在开发环境才使用这个媒体文件路径，不适合在生产环境使用
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from .import views

app_name = 'images'

urlpatterns = [
    # 这是给一张新图片写标题和描述的路由
    path('create/',views.image_create,name='create'),
    # 展示一张图片
    path('detail/<int:id>/<slug:slug>',views.image_detail,name='detail'),
    # ajax请求点赞的路由
    path('like/',views.image_like,name='like'),
    # 显示所有的图片
    path('',views.image_list,name='list'),
    # 最受欢迎的十张图片
    path('ranking/',views.image_ranking,name='ranking'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.

class Image(models.Model):
    # 一对多关系
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name = 'images_created',
                             on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    slug = models.SlugField(max_length=200,blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    # 多对多关系
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name = 'images_liked',
                                        blank = True)
    # 统计点赞数
    total_likes = models.PositiveIntegerField(db_index=True,
                                              default=0)
    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('images:detail',args=[self.id,self.slug])


images/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model =  Image
        fields = ['title','url','description']
        widgets = {
            # 对用户不可见
            'url':forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        # 只允许上传jpg格式的图像
        valid_extensions = ['jpg','jpeg']
        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not \
                match valid image extensions.')
        return url
    
    def save(self,
            force_insert=False,
            force_update=False,
            commit=True):
        '''覆盖了原来的save方法'''
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.',1)[1].lower()
        image_name = f'{name}.{extension}'
        
        # 下载图片
        response = request.urlopen(image_url)
        # 后面的这个image是数据库里的image字段
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse,HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator,EmptyPage,\
    PageNotAnInteger
import redis
from django.conf import settings

from .forms import ImageCreateForm
from .models import Image
from common.decorators import ajax_required
from actions.utils import create_action
# Create your views here.

# 连接redis数据库
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB,
                username=settings.REDIS_USERNAME,
                password=settings.REDIS_PASSWORD)

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)

            new_item.user = request.user
            new_item.save()
            # 添加用户活动
            create_action(request.user,'bookmarked image',new_item)
            messages.success(request,'Image added successfully')

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)

    return render(request,
                  'images/image/create.html',
                  {'section':'images',
                  'form':form}) 


def image_detail(request,id,slug):
    image = get_object_or_404(Image,id=id,slug=slug)
    # 图片访问数量加1
    # 参数是key，key不存在就新建，存在就把值加1
    total_views = r.incr(f'image:{image.id}:views')
    # 图片排序，使用redis的有序集合，
    # 每访问一次，权重score就加1
    # 这个集合的键是image_ranking
    r.zincrby('image_ranking',1,image.id)
    return render(request,
                  'images/image/detail.html',
                  {'section':'images',
                  'image':image,
                  'total_views':total_views})

@ajax_required
@login_required
@require_POST
def image_like(request):
    '''用户点赞'''
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                # 添加用户活动
                create_action(request.user,'likes',image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'error'})


@login_required
def image_list(request):
    '''列出所有图片'''
    images = Image.objects.all()
    paginator = Paginator(images,8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        # 如果是ajax请求，那就是滑到底了，什么也不用返回
        if request.is_ajax():
            return HttpResponse('')
        # 如果不是ajax请求，那就返回最后一页
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'section':'images','images':images})
    return render(request,
                  'images/image/list.html',
                  {'section':'images','images':images})


@login_required
def image_ranking(request):
    '''按照图片访问量来显示图片'''
    image_ranking = r.zrange('image_ranking',0,-1,desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # 获取对应的图片对象
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    # 因为从数据库里查出来之后顺序就还是按照默认的id大小排列了，
    # 下面就是要恢复访问量的降序排列
    most_viewed.sort(key=lambda x:image_ranking_ids.index(x.id))
    return render(request,
                  'images/image/ranking.html',
                  {'section':'images',
                  'most_viewed':most_viewed})
    

images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Bookmark it!">
</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}

{%block content%}
<h1>{{image.title}}</h1>
{% load thumbnail %}
<a href="{{image.image.url}}">
    <!-- 宽是300，高是自适应 ,图像质量是最高-->
    <img src="{% thumbnail image.image 300x0 quality=100 %}" class='image-detail'>
</a>


{% with total_likes=image.users_like.count users_like=image.users_like.all%}
<div class='image-info'>
 <div>
     <span class='count'>
        <span class='total'>{{total_likes}}</span> 
        like{{total_likes|pluralize}}
     </span>
     <span class='count'>
        {{total_views}} view{{total_views|pluralize}}
     </span>
     <a href="#" data-id="{{image.id}}" data-action="{% if request.user in users_like%}un{%endif%}like" class='like button'>
         {% if request.user not in users_like %}
         Like
         {%else%}
         Unlike
         {%endif%}
     </a>
 </div>
 {{image.description|linebreaks}}
</div>

<div class='image-likes'>
    {%for user in users_like %}
    <div>
        <img src="{{user.profile.photo.url}}" >
        <p>{{user.first_name}}</p>
    </div>
    {%empty%}
    Nobody likes this image yet.
    {%endfor%}
</div>
{%endwith%}
{%endblock%}

{%block domready%}
$('a.like').click(function(e){
  e.preventDefault();
  $.post('{% url "images:like" %}',
      {
        id:$(this).data('id'),
        action:$(this).data('action')

      },
      function(data){
          if(data['status']=='ok'){
             var previous_action = $('a.like').data('action');
             //变换data-action属性值
             $('a.like').data('action',previous_action=='like'?'unlike':'like');
             //变换a标签里的文本
             $('a.like').text(previous_action=='like'?'Unlike':'Like');
             //更新总点赞数
             var previous_likes = parseInt($('span.count .total').text());
             $('span.count .total').text(previous_action=='like'?previous_likes+1:previous_likes-1);
          }
      }

  )
})
{%endblock%}

images/templates/images/image/list.html
{% extends 'base.html'%}

{%block title%}Images bookmarked{%endblock%}

{%block content%}
<h1>Images bookmarked</h1>
<div id='image-list'>
    {% include 'images/image/list_ajax.html'%}
</div>
{%endblock%}

{%block domready%}
var page = 1;
var empty_page = false;
var block_request = false;

$(window).scroll(function(){
    var margin = $(document).height()-$(window).height()-200;
    if($(window).scrollTop()>margin && empty_page == false && block_request == false ){
        //防止一个ajax请求还没有结束，又发起另一个
        block_request = true;
        page += 1;
        $.get('?page='+page,function(data){
            //如果返回的是空，就说明已经到底了，以后也不需要再发起请求了
            if(data == ''){
                empty_page = true;
            }
            else{
                block_request = false;
                $('#image-list').append(data);
            }
        });
    }
});

{%endblock%}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images%}
<div class='image'>
    <a href="{{image.get_absolute_url}}">
        {% thumbnail image.image 300x300 crop='smart' as im %}
        <a href="{{image.get_absolute_url}}">
            <img src="{{im.url}}" >
        </a>
    </a>
    <div class='info'>
        <a href="{{image.get_absolute_url}}" class='title'>
            {{image.title}}
        </a>
    </div>

</div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
<h1>Images ranking</h1>
<ol>
{% for image in most_viewed %}
<li>
<a href="{{ image.get_absolute_url }}">
{{ image.title }}
</a>
</li>
{% endfor %}
</ol>
{% endblock %}